### ISSUE TITLE
ERROR in parameter file

### ISSUE THREAD

**Issue by AriesChen-UPC** [robinthibaut/pysgems#117]
I will recheck and reorganization the problem, thank you very much for your reply.

**Comment by robinthibaut** [comment]
Hello!

Thanks for your interest in pysgems, but I do not recognize this example. Can you elaborate a little?

At first glance, it looks like some parameters are missing: `{datafile}`, `{outfl}` and `{trnfl}` should probably be replaced by actual paths, e.g., `c:/users/yourpath/something/`.

I would like to help you but you need to provide more details on what you're trying to accomplish.

Best,
Robin
