### ISSUE TITLE
3D grid

### ISSUE THREAD

**Issue by marcelosilka** [robinthibaut/pysgems#18]
Nice work, your pysgems. 

I found in sgdis.py, line 145, the x_lim = 1 should be z_lim = 1

Best regards,

Marcelo

**Comment by robinthibaut** [comment]
Hi Marcelo,

Thanks a lot !

I fixed the issue.

Kind regards,
Robin

**Comment by marcelosilka** [comment]
Thank you, Robin. That was a funny one, undoubtedly showing that your
business is mining.

Best regards,

Marcelo

Em qua., 24 de mar. de 2021 às 01:41, Robin Thibaut <
***@***.***> escreveu:
